spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/reactive_spring
    username: root
    password: YourStrong!Passw0rd
  datasource:
    url: jdbc:mysql://localhost:3306/reactive_spring
    username: root
    password: YourStrong!Passw0rd
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/reactive_spring
    user: root
    password: YourStrong!Passw0rd
    schemas: reactive_spring
    skip-default-callbacks: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
    ignore-missing-migrations: true
    out-of-order: true
  h2:
    console:
      enabled: true
logging:
  level:
    root: Debug
